In [136]:
import requests
import pandas as pd
import json
import csv

**1. Find the correct API endpoint to retrieve historical data on GDP**

Define a variable `base_url` that is a **string** that is simply the base portion of the Alpha Vantage URL endpoint. That is, if you look at any API call, this is everything before the question mark.

Next, define another variable `API_KEY` that is a **string** and is your Alpha Vantage API key (make one, they're free and you don't need to give a real email!)

Use the [Documentation](https://www.alphavantage.co/documentation/) to help you.

In [127]:
base_url = 'https://www.alphavantage.co/query'
api_key = 'F920J6MHQ9XJ90ZO'

**2. Use Python and the `requests` library to make an API call and retrieve historical GDP data at *the highest level of granularity* (i.e. most frequent that the API allows). Remember to add your own API key to the query.**

You should convert the results to JSON so it behaves like a Python dictionary.

In [146]:
av_response = requests.get(base_url, params = {
    'apikey' : 'F920J6MHQ9XJ90ZO',
    'interval' : 'quarterly',
    'function' : 'REAL_GDP',
    'outputsize' : 'full'
})

In [147]:
av_response.status_code

200

In [148]:
av_response.url

'https://www.alphavantage.co/query?apikey=F920J6MHQ9XJ90ZO&interval=quarterly&function=REAL_GDP&outputsize=full'

In [149]:
gdp.keys()

dict_keys(['name', 'interval', 'unit', 'data'])

**3. Convert the data in this JSON to a Pandas dataframe and export to a csv.**

In [150]:
gdp = av_response.json()

In [153]:
df = pd.DataFrame(gdp['data'])
df

          date     value
0   2025-01-01  5748.144
1   2024-10-01  6001.654
2   2024-07-01  5866.841
3   2024-04-01  5817.169
4   2024-01-01  5638.455
..         ...       ...
88  2003-01-01  3582.767
89  2002-10-01  3712.845
90  2002-07-01  3650.253
91  2002-04-01  3608.496
92  2002-01-01  3501.118

[93 rows x 2 columns]

In [154]:
df.to_csv('gdp.csv')

**4. Next, identify the endpoint for finding daily stock price values and query the VXX ticker.**

Make sure to get as much data as possible using the `outputsize` parameter at this endpoint.

VXX is a mutual fund that that adequately represents the [VIX](https://www.investopedia.com/articles/optioninvestor/09/implied-volatility-contrary-indicator.asp#:~:text=VIX%20measures%20the%20market%27s%20expectation%20of%20volatility%20over,trends%20in%20the%20VIX%20can%20inform%20trading%20strategies.) index that represents the fear and volatility in the market. When VIX (or VXX) is high, fear controls the market, and when VIX (or VXX) is low, people have more confidence in the market.

In [77]:
import pandas as pd
import requests

In [82]:
def get_price_data(symbol):
    base_url = "https://www.alphavantage.co/query"

    av_response = requests.get(base_url, params = {
    'apikey' : 'F920J6MHQ9XJ90ZO',
    'symbol' : symbol,
    'function' : 'TIME_SERIES_DAILY',
    'outputsize' : 'full' })
    
    return pd.DataFrame(av_response.json()['Time Series (Daily)']).T

In [83]:
get_price_data('VXX')

             1. open   2. high    3. low  4. close 5. volume
2025-05-27   55.1300   55.8000   52.8303   52.8800   5036501
2025-05-23   59.0000   59.3600   56.9100   58.7900   6660870
2025-05-22   56.0200   56.3900   54.2109   55.1000   3475021
2025-05-21   53.1400   56.3750   52.1600   55.6600   6869668
2025-05-20   52.2800   53.3600   51.8800   52.0900   4851120
...              ...       ...       ...       ...       ...
2009-02-05  101.6000  103.7900   98.1500   99.1300    243200
2009-02-04   98.2500  100.3900   97.0000   99.7400    153600
2009-02-03  104.1400  104.1400   99.3100   99.3700    172800
2009-02-02  108.1000  108.1000  103.9400  104.2500    307200
2009-01-30  100.0800  105.0100   99.7200  104.5500    211200

[4106 rows x 5 columns]

**5. Cast the result as a dataframe and export it to a csv.**

In [27]:
vxx_data = get_price_data('VXX')

In [28]:
vxx_data.to_csv('vxx_data.csv')

**6. Repeat steps 4 and 5, but this time for VTI**

Use all of the same settings to now gather data for VTI, a mutual fund that consists of _every_ US stock. VTI can be considered an indicator for the overall market.

Again, as in step 5, save this data out to a csv.

In [ ]:
def get_price_data(symbol):
    base_url = "https://www.alphavantage.co/query"

    av_response = requests.get(base_url, params = {
    'apikey' : 'F920J6MHQ9XJ90ZO',
    'symbol' : symbol,
    'function' : 'TIME_SERIES_DAILY',
    'outputsize' : 'full' })
    
    return pd.DataFrame(av_response.json()['Time Series (Daily)']).T

In [ ]:
vti_data = get_price_data('VTI')

In [ ]:
vti_data.to_csv('vti_data.csv')

# Part 2: Cryptocurrencies

Your stakeholders are becoming aware of the rise in cryptocurrencies, and would like to understand the recent growth of this market. Your task is to use the Alpha Vantage API to extract historical data on cryptocurrency market performance, and tell a story about their growth using visuals created in a BI tool of your choice (Tableau/Power BI).

**1. Find the correct API endpoints to retrieve historical data on cryptocurrency prices over time. Daily should be a sufficient level of granularity for your purposes.**

Use any specific cryptocurrency you wish (e.g. Bitcoin) against the US Dollar.

Use the [Documentation](https://www.alphavantage.co/documentation/) to help you.

**2. Use Python to read the data as JSON**

In [66]:
base_url = 'https://www.alphavantage.co/query'
API_KEY = 'F920J6MHQ9XJ90ZO'

In [67]:
av_response = requests.get(base_url, params = {
    'apikey' : 'F920J6MHQ9XJ90ZO',
    'symbol' : 'BTC',
    'function' : 'DIGITAL_CURRENCY_DAILY',
    'market' : 'USD',
    'outputsize' : 'full'
})

In [68]:
av_response.status_code

200

In [69]:
av_response.url

'https://www.alphavantage.co/query?apikey=F920J6MHQ9XJ90ZO&symbol=BTC&function=DIGITAL_CURRENCY_DAILY&market=USD&outputsize=full'

In [70]:
btc = av_response.json()

**3. Identify the key which holds the data itself and export it as a csv.**

In [71]:
btc['Time Series (Digital Currency Daily)']

{'2025-05-28': {'1. open': '108978.45000000',
  '2. high': '109115.00000000',
  '3. low': '108731.38000000',
  '4. close': '109009.84000000',
  '5. volume': '102.90486546'},
 '2025-05-27': {'1. open': '109464.33000000',
  '2. high': '110829.42000000',
  '3. low': '107536.41000000',
  '4. close': '108978.46000000',
  '5. volume': '8827.06474254'},
 '2025-05-26': {'1. open': '109048.41000000',
  '2. high': '110474.41000000',
  '3. low': '108706.04000000',
  '4. close': '109464.32000000',
  '5. volume': '4641.37953944'},
 '2025-05-25': {'1. open': '107794.01000000',
  '2. high': '109371.04000000',
  '3. low': '106632.35000000',
  '4. close': '109048.68000000',
  '5. volume': '2996.99842740'},
 '2025-05-24': {'1. open': '107332.08000000',
  '2. high': '109517.79000000',
  '3. low': '106895.77000000',
  '4. close': '107794.01000000',
  '5. volume': '2611.35605460'},
 '2025-05-23': {'1. open': '111722.54000000',
  '2. high': '111824.07000000',
  '3. low': '106800.01000000',
  '4. close': '107329.61000000',
  '5. volume': '9638.23489571'},
 '2025-05-22': {'1. open': '109697.19000000',
  '2. high': '112000.00000000',
  '3. low': '109217.23000000',
  '4. close': '111722.53000000',
  '5. volume': '11250.38756124'},
 '2025-05-21': {'1. open': '106883.24000000',
  '2. high': '110788.98000000',
  '3. low': '106128.14000000',
  '4. close': '109699.54000000',
  '5. volume': '18333.91491262'},
 '2025-05-20': {'1. open': '105616.21000000',
  '2. high': '107355.00000000',
  '3. low': '104209.18000000',
  '4. close': '106883.24000000',
  '5. volume': '8804.35789335'},
 '2025-05-19': {'1. open': '106488.77000000',
  '2. high': '107137.68000000',
  '3. low': '102105.00000000',
  '4. close': '105616.18000000',
  '5. volume': '10104.32339011'},
 '2025-05-18': {'1. open': '103162.53000000',
  '2. high': '106692.97000000',
  '3. low': '103130.95000000',
  '4. close': '106473.46000000',
  '5. volume': '4130.60889099'},
 '2025-05-17': {'1. open': '103500.03000000',
  '2. high': '103741.98000000',
  '3. low': '102612.00000000',
  '4. close': '103161.07000000',
  '5. volume': '1848.95251021'},
 '2025-05-16': {'1. open': '103786.40000000',
  '2. high': '104616.71000000',
  '3. low': '103125.51000000',
  '4. close': '103500.03000000',
  '5. volume': '6881.58784289'},
 '2025-05-15': {'1. open': '103540.91000000',
  '2. high': '104200.00000000',
  '3. low': '101400.01000000',
  '4. close': '103786.43000000',
  '5. volume': '7563.00946962'},
 '2025-05-14': {'1. open': '104131.20000000',
  '2. high': '104373.00000000',
  '3. low': '102603.27000000',
  '4. close': '103545.38000000',
  '5. volume': '7628.28115726'},
 '2025-05-13': {'1. open': '102800.22000000',
  '2. high': '105038.53000000',
  '3. low': '101447.78000000',
  '4. close': '104131.06000000',
  '5. volume': '8727.62104466'},
 '2025-05-12': {'1. open': '104137.58000000',
  '2. high': '105787.37000000',
  '3. low': '100703.71000000',
  '4. close': '102800.21000000',
  '5. volume': '11005.25730989'},
 '2025-05-11': {'1. open': '104817.83000000',
  '2. high': '104980.89000000',
  '3. low': '103360.22000000',
  '4. close': '104137.62000000',
  '5. volume': '3055.11580217'},
 '2025-05-10': {'1. open': '102986.94000000',
  '2. high': '104997.00000000',
  '3. low': '102831.41000000',
  '4. close': '104821.19000000',
  '5. volume': '3104.17143581'},
 '2025-05-09': {'1. open': '103252.20000000',
  '2. high': '104352.60000000',
  '3. low': '102330.76000000',
  '4. close': '102986.96000000',
  '5. volume': '7318.16790891'},
 '2025-05-08': {'1. open': '97058.33000000',
  '2. high': '104176.05000000',
  '3. low': '96888.25000000',
  '4. close': '103253.49000000',
  '5. volume': '15378.08513550'},
 '2025-05-07': {'1. open': '96843.84000000',
  '2. high': '97738.05000000',
  '3. low': '95800.00000000',
  '4. close': '97058.32000000',
  '5. volume': '8326.90882779'},
 '2025-05-06': {'1. open': '94733.99000000',
  '2. high': '96916.25000000',
  '3. low': '93363.28000000',
  '4. close': '96839.17000000',
  '5. volume': '6163.86755769'},
 '2025-05-05': {'1. open': '94272.54000000',
  '2. high': '95218.82000000',
  '3. low': '93500.01000000',
  '4. close': '94733.99000000',
  '5. volume': '5180.15893934'},
 '2025-05-04': {'1. open': '95865.47000000',
  '2. high': '96312.51000000',
  '3. low': '94151.67000000',
  '4. close': '94272.55000000',
  '5. volume': '2834.39686495'},
 '2025-05-03': {'1. open': '96929.81000000',
  '2. high': '96974.78000000',
  '3. low': '95765.13000000',
  '4. close': '95861.33000000',
  '5. volume': '2077.55675998'},
 '2025-05-02': {'1. open': '96524.98000000',
  '2. high': '97948.56000000',
  '3. low': '96369.69000000',
  '4. close': '96929.81000000',
  '5. volume': '5709.61012071'},
 '2025-05-01': {'1. open': '94182.55000000',
  '2. high': '97546.99000000',
  '3. low': '94136.79000000',
  '4. close': '96524.98000000',
  '5. volume': '8333.27177503'},
 '2025-04-30': {'1. open': '94271.08000000',
  '2. high': '95263.74000000',
  '3. low': '92911.88000000',
  '4. close': '94182.54000000',
  '5. volume': '6511.24661593'},
 '2025-04-29': {'1. open': '95042.56000000',
  '2. high': '95499.00000000',
  '3. low': '93761.26000000',
  '4. close': '94271.09000000',
  '5. volume': '5979.42521239'},
 '2025-04-28': {'1. open': '93780.56000000',
  '2. high': '95652.66000000',
  '3. low': '92829.44000000',
  '4. close': '95042.57000000',
  '5. volume': '7347.77103346'},
 '2025-04-27': {'1. open': '94666.64000000',
  '2. high': '95351.11000000',
  '3. low': '93654.77000000',
  '4. close': '93780.57000000',
  '5. volume': '2304.93789541'},
 '2025-04-26': {'1. open': '94707.79000000',
  '2. high': '95273.52000000',
  '3. low': '93903.01000000',
  '4. close': '94666.64000000',
  '5. volume': '2253.98942317'},
 '2025-04-25': {'1. open': '94021.97000000',
  '2. high': '95976.34000000',
  '3. low': '92880.01000000',
  '4. close': '94708.79000000',
  '5. volume': '14147.35380158'},
 '2025-04-24': {'1. open': '93740.93000000',
  '2. high': '94061.02000000',
  '3. low': '91685.18000000',
  '4. close': '94021.96000000',
  '5. volume': '9318.65682559'},
 '2025-04-23': {'1. open': '93486.57000000',
  '2. high': '94686.00000000',
  '3. low': '91902.19000000',
  '4. close': '93740.92000000',
  '5. volume': '12538.03891773'},
 '2025-04-22': {'1. open': '87513.53000000',
  '2. high': '93952.62000000',
  '3. low': '87077.17000000',
  '4. close': '93489.10000000',
  '5. volume': '19460.09432868'},
 '2025-04-21': {'1. open': '85177.33000000',
  '2. high': '88575.62000000',
  '3. low': '85135.98000000',
  '4. close': '87522.07000000',
  '5. volume': '12581.69779747'},
 '2025-04-20': {'1. open': '85074.59000000',
  '2. high': '85319.21000000',
  '3. low': '83972.82000000',
  '4. close': '85177.34000000',
  '5. volume': '1812.14325365'},
 '2025-04-19': {'1. open': '84466.47000000',
  '2. high': '85625.00000000',
  '3. low': '84353.45000000',
  '4. close': '85074.99000000',
  '5. volume': '1683.18995187'},
 '2025-04-18': {'1. open': '84961.97000000',
  '2. high': '85150.94000000',
  '3. low': '84287.06000000',
  '4. close': '84466.47000000',
  '5. volume': '1884.03911217'},
 '2025-04-17': {'1. open': '84028.71000000',
  '2. high': '85494.94000000',
  '3. low': '83711.69000000',
  '4. close': '84961.97000000',
  '5. volume': '5862.46405539'},
 '2025-04-16': {'1. open': '83622.52000000',
  '2. high': '85526.40000000',
  '3. low': '83088.02000000',
  '4. close': '84028.72000000',
  '5. volume': '8243.05901273'},
 '2025-04-15': {'1. open': '84590.36000000',
  '2. high': '86491.40000000',
  '3. low': '83592.77000000',
  '4. close': '83629.78000000',
  '5. volume': '6460.94144192'},
 '2025-04-14': {'1. open': '83733.07000000',
  '2. high': '85818.06000000',
  '3. low': '83655.27000000',
  '4. close': '84590.36000000',
  '5. volume': '7247.02343319'},
 '2025-04-13': {'1. open': '85271.02000000',
  '2. high': '86092.99000000',
  '3. low': '83010.00000000',
  '4. close': '83733.07000000',
  '5. volume': '3904.15929557'},
 '2025-04-12': {'1. open': '83379.64000000',
  '2. high': '85909.97000000',
  '3. low': '82765.26000000',
  '4. close': '85271.01000000',
  '5. volume': '3972.49282052'},
 '2025-04-11': {'1. open': '79552.34000000',
  '2. high': '84299.00000000',
  '3. low': '78919.94000000',
  '4. close': '83380.47000000',
  '5. volume': '9964.68703141'},
 '2025-04-10': {'1. open': '82593.15000000',
  '2. high': '82730.93000000',
  '3. low': '78387.24000000',
  '4. close': '79552.34000000',
  '5. volume': '11876.12778689'},
 '2025-04-09': {'1. open': '76258.80000000',
  '2. high': '83583.35000000',
  '3. low': '74553.01000000',
  '4. close': '82594.75000000',
  '5. volume': '23584.94464084'},
 '2025-04-08': {'1. open': '79140.02000000',
  '2. high': '80849.98000000',
  '3. low': '76167.35000000',
  '4. close': '76251.64000000',
  '5. volume': '14917.02351692'},
 '2025-04-07': {'1. open': '78370.15000000',
  '2. high': '81223.67000000',
  '3. low': '74420.69000000',
  '4. close': '79140.01000000',
  '5. volume': '26706.52930797'},
 '2025-04-06': {'1. open': '83505.88000000',
  '2. high': '83773.58000000',
  '3. low': '77058.99000000',
  '4. close': '78370.75000000',
  '5. volume': '11014.85947730'},
 '2025-04-05': {'1. open': '83859.78000000',
  '2. high': '84238.35000000',
  '3. low': '82346.61000000',
  '4. close': '83498.25000000',
  '5. volume': '2836.42920662'},
 '2025-04-04': {'1. open': '83178.68000000',
  '2. high': '84720.67000000',
  '3. low': '81643.54000000',
  '4. close': '83860.16000000',
  '5. volume': '14593.03092888'},
 '2025-04-03': {'1. open': '82490.10000000',
  '2. high': '83953.45000000',
  '3. low': '81177.70000000',
  '4. close': '83174.33000000',
  '5. volume': '11800.91106566'},
 '2025-04-02': {'1. open': '85166.92000000',
  '2. high': '88530.00000000',
  '3. low': '82283.01000000',
  '4. close': '82490.08000000',
  '5. volume': '16748.28262337'},
 '2025-04-01': {'1. open': '82534.31000000',
  '2. high': '85566.53000000',
  '3. low': '82403.32000000',
  '4. close': '85170.37000000',
  '5. volume': '9130.97692565'},
 '2025-03-31': {'1. open': '82379.98000000',
  '2. high': '83920.80000000',
  '3. low': '81265.16000000',
  '4. close': '82534.32000000',
  '5. volume': '6887.94694226'},
 '2025-03-30': {'1. open': '82624.06000000',
  '2. high': '83508.98000000',
  '3. low': '81538.88000000',
  '4. close': '82379.98000000',
  '5. volume': '2472.72302228'},
 '2025-03-29': {'1. open': '84381.81000000',
  '2. high': '84584.13000000',
  '3. low': '81608.99000000',
  '4. close': '82616.83000000',
  '5. volume': '3194.24303663'},
 '2025-03-28': {'1. open': '87214.07000000',
  '2. high': '87498.15000000',
  '3. low': '83533.40000000',
  '4. close': '84381.80000000',
  '5. volume': '10031.80008987'},
 '2025-03-27': {'1. open': '87429.61000000',
  '2. high': '87474.54000000',
  '3. low': '87108.87000000',
  '4. close': '87217.48000000',
  '5. volume': '261.49922823'},
 '2025-03-26': {'1. open': '87432.82000000',
  '2. high': '88304.10000000',
  '3. low': '85850.00000000',
  '4. close': '86926.01000000',
  '5. volume': '6885.71986041'},
 '2025-03-25': {'1. open': '87518.09000000',
  '2. high': '88584.34000000',
  '3. low': '86321.97000000',
  '4. close': '87427.88000000',
  '5. volume': '10153.98312373'},
 '2025-03-24': {'1. open': '86092.95000000',
  '2. high': '88804.64000000',
  '3. low': '85533.06000000',
  '4. close': '87523.62000000',
  '5. volume': '13107.50391644'},
 '2025-03-23': {'1. open': '83852.06000000',
  '2. high': '86128.99000000',
  '3. low': '83804.67000000',
  '4. close': '86092.94000000',
  '5. volume': '3467.46945277'},
 '2025-03-22': {'1. open': '84061.96000000',
  '2. high': '84517.75000000',
  '3. low': '83659.69000000',
  '4. close': '83852.03000000',
  '5. volume': '2108.51345069'},
 '2025-03-21': {'1. open': '84183.41000000',
  '2. high': '84809.72000000',
  '3. low': '83100.00000000',
  '4. close': '84061.96000000',
  '5. volume': '6257.63558757'},
 '2025-03-20': {'1. open': '86877.97000000',
  '2. high': '87492.87000000',
  '3. low': '83596.75000000',
  '4. close': '84183.42000000',
  '5. volume': '9880.31696275'},
 '2025-03-19': {'1. open': '82699.53000000',
  '2. high': '87045.45000000',
  '3. low': '82535.53000000',
  '4. close': '86877.96000000',
  '5. volume': '13053.65803714'},
 '2025-03-18': {'1. open': '84011.39000000',
  '2. high': '84029.67000000',
  '3. low': '81125.00000000',
  '4. close': '82698.76000000',
  '5. volume': '7316.63296603'},
 '2025-03-17': {'1. open': '82562.50000000',
  '2. high': '84758.46000000',
  '3. low': '82416.98000000',
  '4. close': '84011.40000000',
  '5. volume': '7785.97733364'},
 '2025-03-16': {'1. open': '84351.45000000',
  '2. high': '85092.35000000',
  '3. low': '81969.44000000',
  '4. close': '82562.57000000',
  '5. volume': '4059.89765099'},
 '2025-03-15': {'1. open': '83989.86000000',
  '2. high': '84690.43000000',
  '3. low': '83612.24000000',
  '4. close': '84351.46000000',
  '5. volume': '2331.92028578'},
 '2025-03-14': {'1. open': '81071.50000000',
  '2. high': '85318.61000000',
  '3. low': '80771.17000000',
  '4. close': '83980.49000000',
  '5. volume': '10857.45703924'},
 '2025-03-13': {'1. open': '83659.45000000',
  '2. high': '84310.80000000',
  '3. low': '79890.00000000',
  '4. close': '81073.43000000',
  '5. volume': '10504.15100874'},
 '2025-03-12': {'1. open': '82911.81000000',
  '2. high': '84442.69000000',
  '3. low': '80572.21000000',
  '4. close': '83659.43000000',
  '5. volume': '12612.03125479'},
 '2025-03-11': {'1. open': '78548.18000000',
  '2. high': '83600.00000000',
  '3. low': '76555.00000000',
  '4. close': '82914.51000000',
  '5. volume': '17096.37980265'},
 '2025-03-10': {'1. open': '80708.21000000',
  '2. high': '84033.66000000',
  '3. low': '77389.00000000',
  '4. close': '78544.71000000',
  '5. volume': '21375.10120997'},
 '2025-03-09': {'1. open': '86206.64000000',
  '2. high': '86480.00000000',
  '3. low': '80000.00000000',
  '4. close': '80699.17000000',
  '5. volume': '7565.44749561'},
 '2025-03-08': {'1. open': '86753.30000000',
  '2. high': '86863.38000000',
  '3. low': '85200.00000000',
  '4. close': '86206.69000000',
  '5. volume': '3023.24786650'},
 '2025-03-07': {'1. open': '89915.02000000',
  '2. high': '91280.00000000',
  '3. low': '84608.27000000',
  '4. close': '86756.98000000',
  '5. volume': '27137.20223020'},
 '2025-03-06': {'1. open': '90607.73000000',
  '2. high': '92817.29000000',
  '3. low': '87790.50000000',
  '4. close': '89921.85000000',
  '5. volume': '13302.87500105'},
 '2025-03-05': {'1. open': '87247.93000000',
  '2. high': '91000.00000000',
  '3. low': '86329.22000000',
  '4. close': '90603.73000000',
  '5. volume': '14900.93396554'},
 '2025-03-04': {'1. open': '86161.09000000',
  '2. high': '88977.27000000',
  '3. low': '81444.00000000',
  '4. close': '87249.96000000',
  '5. volume': '23130.37098654'},
 '2025-03-03': {'1. open': '94265.47000000',
  '2. high': '94415.61000000',
  '3. low': '85007.01000000',
  '4. close': '86161.10000000',
  '5. volume': '22691.67068614'},
 '2025-03-02': {'1. open': '86018.82000000',
  '2. high': '95128.88000000',
  '3. low': '85003.35000000',
  '4. close': '94265.48000000',
  '5. volume': '16751.22972996'},
 '2025-03-01': {'1. open': '84297.74000000',
  '2. high': '86534.96000000',
  '3. low': '83772.54000000',
  '4. close': '86018.76000000',
  '5. volume': '6852.54412620'},
 '2025-02-28': {'1. open': '84627.50000000',
  '2. high': '85116.19000000',
  '3. low': '78167.81000000',
  '4. close': '84297.73000000',
  '5. volume': '30755.74245077'},
 '2025-02-27': {'1. open': '84111.77000000',
  '2. high': '86993.87000000',
  '3. low': '82554.11000000',
  '4. close': '84625.19000000',
  '5. volume': '16836.55524727'},
 '2025-02-26': {'1. open': '88583.17000000',
  '2. high': '89305.68000000',
  '3. low': '82111.12000000',
  '4. close': '84111.78000000',
  '5. volume': '21568.55463119'},
 '2025-02-25': {'1. open': '91509.88000000',
  '2. high': '92549.99000000',
  '3. low': '85836.18000000',
  '4. close': '88583.74000000',
  '5. volume': '31587.91715546'},
 '2025-02-24': {'1. open': '96266.23000000',
  '2. high': '96515.41000000',
  '3. low': '91300.00000000',
  '4. close': '91510.82000000',
  '5. volume': '12644.04350070'},
 '2025-02-23': {'1. open': '96578.49000000',
  '2. high': '96679.93000000',
  '3. low': '95243.91000000',
  '4. close': '96265.98000000',
  '5. volume': '3787.84705335'},
 '2025-02-22': {'1. open': '96157.03000000',
  '2. high': '96982.52000000',
  '3. low': '95767.95000000',
  '4. close': '96582.12000000',
  '5. volume': '7324.02366243'},
 '2025-02-21': {'1. open': '98347.20000000',
  '2. high': '99517.52000000',
  '3. low': '94721.92000000',
  '4. close': '96157.03000000',
  '5. volume': '19298.23921958'},
 '2025-02-20': {'1. open': '96632.03000000',
  '2. high': '98768.54000000',
  '3. low': '96419.07000000',
  '4. close': '98347.20000000',
  '5. volume': '10582.84622768'},
 '2025-02-19': {'1. open': '95612.97000000',
  '2. high': '96880.00000000',
  '3. low': '95000.01000000',
  '4. close': '96632.03000000',
  '5. volume': '6945.44897339'},
 '2025-02-18': {'1. open': '95781.80000000',
  '2. high': '96730.00000000',
  '3. low': '93333.00000000',
  '4. close': '95607.40000000',
  '5. volume': '8867.39878431'},
 '2025-02-17': {'1. open': '96119.88000000',
  '2. high': '97050.64000000',
  '3. low': '95200.00000000',
  '4. close': '95781.80000000',
  '5. volume': '3533.01273263'},
 '2025-02-16': {'1. open': '97596.54000000',
  '2. high': '97738.22000000',
  '3. low': '96057.68000000',
  '4. close': '96119.88000000',
  '5. volume': '2174.29326885'},
 '2025-02-15': {'1. open': '97507.94000000',
  '2. high': '97997.85000000',
  '3. low': '97225.01000000',
  '4. close': '97596.94000000',
  '5. volume': '1626.51929078'},
 '2025-02-14': {'1. open': '96625.29000000',
  '2. high': '98890.11000000',
  '3. low': '96268.56000000',
  '4. close': '97509.03000000',
  '5. volume': '7744.67640105'},
 '2025-02-13': {'1. open': '97864.28000000',
  '2. high': '98100.00000000',
  '3. low': '95220.00000000',
  '4. close': '96625.29000000',
  '5. volume': '6803.60789270'},
 '2025-02-12': {'1. open': '95770.95000000',
  '2. high': '98119.98000000',
  '3. low': '94066.92000000',
  '4. close': '97862.53000000',
  '5. volume': '9078.50356189'},
 '2025-02-11': {'1. open': '97451.66000000',
  '2. high': '98500.00000000',
  '3. low': '94831.07000000',
  '4. close': '95774.08000000',
  '5. volume': '7737.05105717'},
 '2025-02-10': {'1. open': '96481.47000000',
  '2. high': '98367.23000000',
  '3. low': '95257.20000000',
  '4. close': '97444.41000000',
  '5. volume': '6375.72539123'},
 '2025-02-09': {'1. open': '96476.24000000',
  '2. high': '97342.28000000',
  '3. low': '94730.67000000',
  '4. close': '96475.82000000',
  '5. volume': '3417.87009701'},
 '2025-02-08': {'1. open': '96536.93000000',
  '2. high': '96919.05000000',
  '3. low': '95682.33000000',
  '4. close': '96476.25000000',
  '5. volume': '2972.45715184'},
 '2025-02-07': {'1. open': '96575.24000000',
  '2. high': '100235.79000000',
  '3. low': '95614.96000000',
  '4. close': '96537.08000000',
  '5. volume': '12171.82534167'},
 '2025-02-06': {'1. open': '96635.62000000',
  '2. high': '99182.15000000',
  '3. low': '95674.96000000',
  '4. close': '96564.62000000',
  '5. volume': '9168.94674634'},
 '2025-02-05': {'1. open': '97795.06000000',
  '2. high': '99230.49000000',
  '3. low': '96161.01000000',
  '4. close': '96638.33000000',
  '5. volume': '9308.59185883'},
 '2025-02-04': {'1. open': '101460.15000000',
  '2. high': '101812.23000000',
  '3. low': '96145.76000000',
  '4. close': '97795.05000000',
  '5. volume': '14168.70316610'},
 '2025-02-03': {'1. open': '97676.53000000',
  '2. high': '102599.85000000',
  '3. low': '91178.01000000',
  '4. close': '101460.20000000',
  '5. volume': '31328.72219576'},
 '2025-02-02': {'1. open': '100623.88000000',
  '2. high': '101459.84000000',
  '3. low': '96179.00000000',
  '4. close': '97676.52000000',
  '5. volume': '10366.65062753'},

In [72]:
import pandas as pd
import requests

In [73]:
pd.DataFrame(btc['Time Series (Digital Currency Daily)']).T

,1. open,2. high,3. low,4. close,5. volume
2025-05-28,108978.45000000,109115.00000000,108731.38000000,109009.84000000,102.90486546
2025-05-27,109464.33000000,110829.42000000,107536.41000000,108978.46000000,8827.06474254
2025-05-26,109048.41000000,110474.41000000,108706.04000000,109464.32000000,4641.37953944
2025-05-25,107794.01000000,109371.04000000,106632.35000000,109048.68000000,2996.99842740
2025-05-24,107332.08000000,109517.79000000,106895.77000000,107794.01000000,2611.35605460
...,...,...,...,...,...
2024-06-17,66629.38000000,67274.96000000,65050.00000000,66481.81000000,14487.64060903
2024-06-16,66192.00000000,66931.18000000,65999.00000000,66628.75000000,2118.65163435
2024-06-15,66004.36000000,66428.57000000,65800.86000000,66192.00000000,2004.14215480
2024-06-14,66746.46000000,67322.72000000,65005.00000000,66004.39000000,11520.15791899
2024-06-13,68248.59000000,68474.49000000,66200.00000000,66738.85000000,11916.13211129

In [74]:
btc = pd.DataFrame(btc['Time Series (Digital Currency Daily)']).T
btc.to_csv('btc.csv')

**ETH**

In [155]:
import pandas as pd
import requests

In [156]:
base_url = 'https://www.alphavantage.co/query'
API_KEY = 'F920J6MHQ9XJ90ZO'

In [157]:
av_response = requests.get(base_url, params = {
    'apikey' : 'F920J6MHQ9XJ90ZO',
    'symbol' : 'ETH',
    'function' : 'DIGITAL_CURRENCY_DAILY',
    'market' : 'USD',
    'outputsize' : 'full'
})

In [158]:
av_response.status_code

200

In [159]:
av_response.url

'https://www.alphavantage.co/query?apikey=F920J6MHQ9XJ90ZO&symbol=ETH&function=DIGITAL_CURRENCY_DAILY&market=USD&outputsize=full'

In [164]:
eth = av_response.json()

In [166]:
pd.DataFrame(eth['Time Series (Digital Currency Daily)']).T

,1. open,2. high,3. low,4. close,5. volume
2025-05-29,2682.44000000,2700.76000000,2671.43000000,2696.38000000,4882.15978149
2025-05-28,2662.18000000,2690.33000000,2609.90000000,2682.16000000,115485.45833737
2025-05-27,2564.71000000,2713.78000000,2510.54000000,2662.04000000,165985.50097174
2025-05-26,2552.44000000,2600.80000000,2526.98000000,2564.32000000,56977.02353915
2025-05-25,2531.34000000,2555.30000000,2463.37000000,2552.32000000,58254.46870874
...,...,...,...,...,...
2024-06-18,3509.81000000,3515.87000000,3351.00000000,3482.06000000,129044.70825538
2024-06-17,3622.53000000,3640.00000000,3463.38000000,3509.55000000,111781.88622712
2024-06-16,3566.82000000,3651.51000000,3538.74000000,3622.10000000,44147.59671264
2024-06-15,3479.53000000,3591.87000000,3470.96000000,3566.69000000,56700.50673905
2024-06-14,3467.90000000,3529.83000000,3360.62000000,3479.53000000,102617.12125958

In [167]:
eth = pd.DataFrame(eth['Time Series (Digital Currency Daily)']).T
eth.to_csv('eth.csv')

**XRP**

In [177]:
import pandas as pd
import requests

In [178]:
base_url = 'https://www.alphavantage.co/query'
API_KEY = 'F920J6MHQ9XJ90ZO'

In [191]:
av_response = requests.get(base_url, params = {
    'apikey' : 'F920J6MHQ9XJ90ZO',
    'symbol' : 'XRP',
    'function' : 'DIGITAL_CURRENCY_DAILY',
    'market' : 'USD',
    'outputsize' : 'full'
})

In [192]:
av_response.status_code

200

In [193]:
av_response.url

'https://www.alphavantage.co/query?apikey=F920J6MHQ9XJ90ZO&symbol=XRP&function=DIGITAL_CURRENCY_DAILY&market=USD&outputsize=full'

In [194]:
xrp = av_response.json()

In [195]:
pd.DataFrame(xrp['Time Series (Digital Currency Daily)']).T

               1. open     2. high      3. low    4. close           5. volume
2025-05-29  2.27470000  2.28270000  2.26770000  2.27900000    1250056.83797700
2025-05-28  2.31800000  2.32430000  2.22680000  2.27490000   58132977.10810700
2025-05-27  2.31100000  2.35520000  2.26820000  2.31810000   47373807.94176600
2025-05-26  2.34310000  2.36000000  2.29650000  2.31110000   39148368.91412500
2025-05-25  2.33130000  2.34500000  2.26660000  2.34300000   52545379.15956300
...                ...         ...         ...         ...                 ...
2024-06-18  0.50450000  0.55660000  0.47030000  0.49080000  121417223.31156300
2024-06-17  0.48900000  0.52090000  0.48370000  0.50460000  103514679.34570000
2024-06-16  0.49050000  0.49930000  0.48750000  0.48890000   28362539.96632300
2024-06-15  0.47430000  0.50490000  0.47370000  0.49050000   39102015.54402600
2024-06-14  0.47670000  0.48110000  0.46010000  0.47440000   60712880.37992600

[350 rows x 5 columns]

In [196]:
xrp = pd.DataFrame(xrp['Time Series (Digital Currency Daily)']).T
xrp.to_csv('xrp.csv')

**ADA**

In [197]:
import pandas as pd
import requests

In [198]:
base_url = 'https://www.alphavantage.co/query'
API_KEY = 'F920J6MHQ9XJ90ZO'

In [199]:
av_response = requests.get(base_url, params = {
    'apikey' : 'F920J6MHQ9XJ90ZO',
    'symbol' : 'ADA',
    'function' : 'DIGITAL_CURRENCY_DAILY',
    'market' : 'USD',
    'outputsize' : 'full'
})

In [200]:
av_response.status_code

200

In [201]:
av_response.url

'https://www.alphavantage.co/query?apikey=F920J6MHQ9XJ90ZO&symbol=ADA&function=DIGITAL_CURRENCY_DAILY&market=USD&outputsize=full'

In [202]:
ada = av_response.json()

In [203]:
pd.DataFrame(ada['Time Series (Digital Currency Daily)']).T

               1. open     2. high      3. low    4. close          5. volume
2025-05-29  0.74800000  0.75130000  0.74400000  0.74980000    564400.62501525
2025-05-28  0.75870000  0.76160000  0.73210000  0.74790000  24010559.51510059
2025-05-27  0.76050000  0.77590000  0.74350000  0.75870000  26111665.71350198
2025-05-26  0.76040000  0.77750000  0.75130000  0.76040000  20696987.34997957
2025-05-25  0.74720000  0.76080000  0.72810000  0.76030000  25704413.60697444
...                ...         ...         ...         ...                ...
2024-06-18  0.40120000  0.40250000  0.36610000  0.38330000  45083745.37674993
2024-06-17  0.41670000  0.42070000  0.39000000  0.40100000  16717608.12715805
2024-06-16  0.41380000  0.41900000  0.40890000  0.41650000   6096155.62048681
2024-06-15  0.41180000  0.41550000  0.40790000  0.41370000   8910939.45174182
2024-06-14  0.42090000  0.42450000  0.40000000  0.41190000  18469212.36628998

[350 rows x 5 columns]

In [204]:
ada = pd.DataFrame(ada['Time Series (Digital Currency Daily)']).T
ada.to_csv('ada.csv')

**SOL**

In [206]:
import pandas as pd
import requests

In [207]:
base_url = 'https://www.alphavantage.co/query'
API_KEY = 'F920J6MHQ9XJ90ZO'

In [208]:
av_response = requests.get(base_url, params = {
    'apikey' : 'F920J6MHQ9XJ90ZO',
    'symbol' : 'SOL',
    'function' : 'DIGITAL_CURRENCY_DAILY',
    'market' : 'USD',
    'outputsize' : 'full'
})

In [209]:
av_response.status_code

200

In [210]:
av_response.url

'https://www.alphavantage.co/query?apikey=F920J6MHQ9XJ90ZO&symbol=SOL&function=DIGITAL_CURRENCY_DAILY&market=USD&outputsize=full'

In [211]:
sol = av_response.json()

In [212]:
pd.DataFrame(sol['Time Series (Digital Currency Daily)']).T

,1. open,2. high,3. low,4. close,5. volume
2025-05-29,172.27000000,172.40000000,171.40000000,172.00000000,25447.50813758
2025-05-28,176.77000000,177.50000000,168.99000000,172.28000000,835021.66888198
2025-05-27,174.99000000,179.50000000,171.29000000,176.80000000,948922.05842624
2025-05-26,175.81000000,179.12000000,173.55000000,174.97000000,686840.92973788
2025-05-25,175.96000000,176.96000000,169.20000000,175.80000000,776842.78268605
...,...,...,...,...,...
2024-06-18,143.24000000,143.76000000,128.00000000,137.37000000,1722471.07323113
2024-06-17,151.22000000,151.73000000,139.77000000,143.25000000,744074.60029120
2024-06-16,145.45000000,151.26000000,142.97000000,151.22000000,348354.54491309
2024-06-15,142.98000000,145.68000000,142.84000000,145.45000000,285002.23960479
2024-06-14,147.23000000,148.94000000,139.56000000,142.98000000,944501.87423291

In [213]:
sol = pd.DataFrame(sol['Time Series (Digital Currency Daily)']).T
sol.to_csv('sol.csv')